language: node_js
node_js:
  - "5.7"
  - "5.0"
  - "4.3"
  - "4.0"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.6"
  - "0.4"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.4" ] || [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.8" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then npm run travis-test-only ; else npm run travis ; fi'
